const $=id=>document.getElementById(id);const show=(id,data)=>$(id).textContent=typeof data==='string'?data:JSON.stringify(data,null,2);const API_BASE=location.protocol==='file:'?'http://127.0.0.1:8000':'';const api=async(path,options)=>{const r=await fetch(`${API_BASE}${path}`,options);const data=await r.json();if(!r.ok)throw new Error(data.detail||'请求失败');return data};
const intentNames={course_fact:'课程基础信息',course_compare:'课程比较',degree_audit:'毕业规则',schedule_plan:'课程课表信息',personalized_plan:'个性化规划',community_discussion:'社区讨论',clarification:'需要澄清'};
const agentNames={course_info:'课程信息 Agent',academic_rules:'学业规则 Agent',schedule_workload:'课程课表信息 Agent',planner:'规划 Agent'};
function renderConsultation(data){const chain=data.chain||{};let html=`<div class="answer"><h3>咨询结果</h3><p><b>识别需求：</b>${intentNames[chain.intent]||chain.intent}</p>`;if(chain.primary_agent)html+=`<p><b>负责 Agent：</b>${agentNames[chain.primary_agent]||chain.primary_agent}</p>`;const profileNeeded=['personalized_plan','course_compare','degree_audit'].includes(chain.intent);if(!data.profile_found&&profileNeeded)html+='<p class="warning">请先到“我的”页面保存个人画像，系统才能进行个性化选课规划。</p>';if(chain.blocker)html+=`<p class="warning">${chain.blocker}</p>`;const offerings=chain.facts&&chain.facts.offerings||[];if(offerings.length){html+='<h3>课程课表信息</h3>'+offerings.map(o=>`<div class="offering"><b>${o.course_code} ${o.section||''}</b><br>CRN：${o.crn||'—'}<br>地点：${o.building||'—'} ${o.room||'—'}<br>时间：${o.date_start||''} - ${o.date_end||''} ${formatSlots(o.slots)}<br>教师：${o.instructor||'—'}<br>语言：${o.medium||'—'}</div>`).join('')}else if(chain.evidence&&chain.evidence.length){html+='<p><b>已找到官方依据：</b></p><ul>'+chain.evidence.slice(0,5).map(e=>`<li>${e.title} <span class="muted">（${e.source_type}）</span></li>`).join('')+'</ul>'}html+='<p class="muted">系统只展示基于官方资料的规划结果，不会操作 AIMS 注册。</p></div>';return html}
function formatSlots(slots){return (slots||[]).map(s=>`周${['一','二','三','四','五','六','日'][(s.weekday||1)-1]} ${String(Math.floor(s.start_minute/60)).padStart(2,'0')}:${String(s.start_minute%60).padStart(2,'0')}-${String(Math.floor(s.end_minute/60)).padStart(2,'0')}:${String(s.end_minute%60).padStart(2,'0')}`).join('；')||'时间未提供'}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(s=>s.classList.remove('active'));$(b.dataset.tab).classList.add('active')});
$('saveProfile').onclick=async()=>{try{const completed=$('completed').value.split(',').map(x=>x.trim()).filter(Boolean).map(course_code=>({course_code,status:'passed'}));await api(`/profiles/${encodeURIComponent($('userId').value)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({programme:'DSC',major_track:$('track').value,catalogue_year:$('year').value,completed_courses:completed,interests:$('interests').value.split(',').map(x=>x.trim()).filter(Boolean)})});$('profileResult').textContent='画像已保存';await loadProfileProgress()}catch(e){$('profileResult').textContent=e.message}};
async function loadProfileProgress(){try{const p=await api(`/profiles/${encodeURIComponent($('userId').value)}/progress`);const percent=Math.min(100,Math.round(p.completed_credits/p.graduation_credits*100));const completed=(p.completed_courses||[]).map(c=>`<span class="course-chip"><b>${c.course_code}</b><small>${escapeHtml(c.title)} · ${c.credits} 学分</small></span>`).join('')||'<p class="muted">还没有记录已修课程。</p>';const missing=(p.missing_core_courses||[]).map(c=>`<li><b>${c.course_code}</b> ${escapeHtml(c.title)} <span>${c.credits} 学分</span></li>`).join('')||'<li class="complete">核心课程已全部记录</li>';const req=p.requirements||{},ge=req.ge||{},college=req.college_specified||{},school=req.college_school||{},elective=req.major_electives||{};$('profileProgress').innerHTML=`<div class="progress-header"><div><span class="eyebrow">${escapeHtml(p.major_track)} · ${escapeHtml(p.catalogue_year)}</span><h3>毕业进度</h3></div><strong>${p.completed_credits} / ${p.graduation_credits}<small> 已修学分</small></strong></div><div class="progress-track"><i style="width:${percent}%"></i></div><p class="progress-caption">还需完成约 <b>${p.remaining_credits} 学分</b>，专业要求参考 ${escapeHtml(p.major_requirement_range)}。</p><section class="profile-block"><h4>已修课程</h4><div class="course-chips">${completed}</div></section><section class="profile-block"><h4>毕业要求概览</h4><div class="requirement-cards"><div><b>通识教育</b><strong>${ge.missing_named_courses?.length||0}</strong><small>门指定课程待完成（总要求 ${ge.target_credits||31} 学分）</small></div><div><b>学院指定课程</b><strong>${college.missing_courses?.length||0}</strong><small>门待完成（${college.target_credits||9} 学分）</small></div><div><b>学院/学校要求</b><strong>${school.missing_courses?.length||0}</strong><small>门待完成（${school.target_credits||8} 学分）</small></div><div><b>专业选修</b><strong>${elective.remaining_credits||0}</strong><small>学分待完成（已修 ${elective.completed_credits||0}）</small></div></div></section><section class="profile-block"><h4>核心课程缺口 <span>${(p.missing_core_courses||[]).length} 门</span></h4><ul class="missing-list">${missing}</ul></section>`}catch(e){$('profileProgress').innerHTML=`<p class="muted">填写并保存画像后即可查看毕业进度。</p>`}}
loadProfileProgress();
$('ask').onclick=async()=>{try{$('consultResult').innerHTML=renderConsultation(await api('/consultation/context',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:$('userId').value,message:$('question').value,term_id:$('consultTerm').value})}))}catch(e){show('consultResult',e.message)}};
let allCourseCards=[];
function courseSubjectMatches(course, selected){if(!selected)return true;if(selected==='OTHER')return !['DSC','CS','MA','GE'].includes(course.course_code.replace(/[0-9].*$/,''));return course.course_code.startsWith(selected)}
function renderCourseCards(){const query=($('courseSearch').value||'').trim().toLowerCase(),subject=$('courseSubject').value,credits=$('courseCredits').value;const filtered=allCourseCards.filter(c=>(!query||`${c.course_code} ${c.title}`.toLowerCase().includes(query))&&courseSubjectMatches(c,subject)&&(!credits||String(c.credits)===credits));$('courseCount').textContent=`显示 ${filtered.length} / ${allCourseCards.length} 门课程`;$('courseCards').innerHTML=filtered.length?filtered.map(c=>`<button class="course-card" data-code="${c.course_code}"><strong>${c.course_code}</strong><br>${escapeHtml(c.title)}<br><small>${c.credits} credits</small></button>`).join(''):'<p class="muted">没有符合条件的课程。</p>';document.querySelectorAll('.course-card').forEach(b=>b.onclick=()=>{window.location.href=`course.html?code=${encodeURIComponent(b.dataset.code)}`})}
async function loadCourseCards(){try{const data=await api('/courses');allCourseCards=data.courses;renderCourseCards()}catch(e){$('courseCards').textContent=e.message}}
$('courseSearch').oninput=renderCourseCards;$('courseSubject').onchange=renderCourseCards;$('courseCredits').onchange=renderCourseCards;$('clearCourseFilters').onclick=()=>{$('courseSearch').value='';$('courseSubject').value='';$('courseCredits').value='';renderCourseCards()};
async function loadCourseDetail(code){try{const [detail,reviews]=await Promise.all([api(`/courses/${code}/details?term_id=2026-A`),api(`/courses/${code}/reviews`)]);const c=detail.course,community=reviews;const dist=Object.entries(community.rating_distribution||{}).map(([r,n])=>`<div class="bar-row"><span>${r}★</span><div class="bar"><i style="width:${community.review_count?Math.round(n/community.review_count*100):0}%"></i></div><small>${n}</small></div>`).join('');const offerings=(detail.aims_offerings||[]).map(o=>`<li><b>${o.section}</b> · CRN ${o.crn} · ${o.building||''} ${o.room||''} · ${formatSlots(o.slots)}</li>`).join('')||'<li>本学期暂无已发布 Section</li>';const reviewsHtml=(community.reviews||[]).map(r=>`<article class="review"><b>${r.overall_rating}★</b><span>${r.term_id}</span><p>${escapeHtml(r.content)}</p></article>`).join('')||'<p class="muted">暂无评价，欢迎成为第一位分享体验的同学。</p>';$('courseDetail').hidden=false;$('courseDetail').innerHTML=`<button class="back-btn" onclick="$('courseDetail').hidden=true">返回课程列表</button><div class="course-hero"><div><span class="eyebrow">${c.subject} · ${c.catalogue_year}</span><h3>${c.code} ${c.title}</h3><p>${c.offering_academic_unit} · ${c.credits} credits · ${c.duration_terms} semester(s)</p></div></div><div class="detail-grid"><section class="detail-card"><h4>课程信息</h4><p><b>先修课：</b>${formatPrerequisite(c.prerequisite)}</p><p><b>Catalogue：</b><a href="${c.official_url}" target="_blank">查看官方课程页</a></p></section><section class="detail-card"><h4>同学评价概览</h4><div class="stat-grid"><div><strong>${community.average_rating??'—'}</strong><small>平均评分</small></div><div><strong>${community.review_count}</strong><small>条评价</small></div><div><strong>${community.average_difficulty??'—'}</strong><small>难度指数</small></div><div><strong>${community.average_workload??'—'}</strong><small>工作量指数</small></div></div><div class="bars">${dist}</div></section></div><section class="detail-card"><h4>Semester A 2026/27 课表</h4><ul class="offering-list">${offerings}</ul><p class="muted">AIMS 为已发布课表快照，不代表实时可注册状态。</p></section><section class="detail-card"><h4>文字评价</h4>${reviewsHtml}</section>`;window.scrollTo({top:$('courseDetail').offsetTop-20,behavior:'smooth'})}catch(e){$('courseDetail').hidden=false;$('courseDetail').textContent=e.message}}
function formatPrerequisite(p){if(!p)return'无';const all=p.required_all||[],groups=p.required_any_groups||[];return [...all,...groups.map(g=>`(${g.join(' 或 ')})`)].join(' 且 ')||'无'}
loadCourseCards();
new MutationObserver(()=>document.querySelectorAll('.course-detail .muted').forEach(el=>{if(el.textContent.includes('AIMS'))el.textContent='详情请以 AIMS 系统实际显示为准。'})).observe($('courseDetail'),{childList:true,subtree:true});
const _renderConsultation = renderConsultation;
renderConsultation = data => {
  let html = _renderConsultation(data);
  const question = String(data.message || '').toLowerCase();
  const asksForFullSchedule = /(详细|全部|完整|课表|section|crn)/i.test(question);
  if (!asksForFullSchedule) {
    html = html.replace(/<h3>课程课表信息<\/h3>[\s\S]*?(?=<p class="muted">)/, '');
  }
  html = html.replace(/<p><b>识别需求：<\/b>[\s\S]*?<\/p>/, '').replace(/<p><b>负责 Agent：<\/b>[\s\S]*?<\/p>/, '');
  const answer = data.chain && data.chain.answer;
  if (answer) return `<div class="answer"><div class="llm-answer"><div>${formatAnswer(answer)}</div></div></div>`;
  return html;
};
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function formatAnswer(value){return escapeHtml(value).replace(/##\s*/g,'<br>').replace(/\s+-\s+/g,'<br>• ').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/^<br>/,'');}
